from google.genai import types

async def display_state(session_service, app_name, session_id, user_id, label = "CURRENT STATE"):
    """
        Displays the session state at the time of invocation
    """
    try:
        # get the session 
        session = await session_service.get_session(
            app_name = app_name, session_id = session_id, user_id = user_id
        )

        print(f"{'-'*10} {label} {'-'*10}")

        userName = session.state.get("user_name", "Unknown")
        print(f"User name: {userName}")

        todo_list = session.state.get("todo_list", [])
        if todo_list:
            print(f"To Do list:")
            for idx, todo in enumerate(todo_list, 1):
                print(f"\t{idx}) {todo}")
        else:
            print(f"ToDos: None")
        
        print(f"{'-' * (22 + len(label))}")
        
    except Exception as e:
        print(f"Error while fetching ad displaying the session state: {e}")
        print(f"{'-' * (22 + len(label))}")
    return

async def process_agent_response(event):
    """
        Process agent response event
    """
    # Log event info
    print(f"Event id: {event.id} \t Author: {event.author}")

    # check for differnt parts in event response
    has_specific_parts = False
    if event.content and event.content.parts:
        for part in event.content.parts:
            if hasattr(part, "executable_code") and part.executable_code:
                # Access the generated code using .code
                print(f"Debug: Code generated by agent: \n```python\n{part.executable_code}\n```")
                has_specific_parts = True
            elif hasattr(part, "code_execution_result") and part.code_execution_result:
                print(f"Debug: outcome of code execution: {part.code_execution_result.outcome}\n"
                      f"Debug: output of code execution: {part.code_execution_result.output}")
                has_specific_parts = True
            elif hasattr(part, "tool_response") and part.tool_response:
                print(f"Debug: Tool response: {part.tool_response.output}")
                has_specific_parts = True
            elif hasattr(part, "text") and part.text and not part.text.isspace():
                print(f"Debug: {part.text.strip()}")
                has_specific_parts = True
    
    # get final response of the event
    final_response = None
    if event.is_final_response():
        if(
            event.content
            and event.content.parts
            and hasattr(event.content.parts[0], "text")
            and event.content.parts[0].text
        ):
            # get the final response of the agent and remove trailing spaces
            final_response = event.content.parts[0].text.strip()
            print(f"Agent: {final_response}\n")
        else: 
            print(f"No text content present in the final response of the agent.")
    return final_response

async def call_agent_async(runner, message, session_id, user_id):
    """Call the agent asynchronously with the user's query."""
    final_response = None

    # display state of the session before event
    await display_state(runner.session_service, runner.app_name, session_id, user_id, label="INITIAL STATE")

    try:
        query = types.Content(
            role = "user", parts = [types.Part(text=message)]
        )
        async for event in runner.run_async(
            user_id = user_id,
            session_id = session_id,
            new_message = query
        ):
            response = await process_agent_response(event)
            if response:
                final_response = response
    except Exception as e:
        print(f"Error during agent call: {e}")

    # display state of the session after event
    await display_state(runner.session_service, runner.app_name, session_id, user_id)
    return final_response